services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  sender:
    build: ./send
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  receiver:
    build: ./receive
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped